<?php

require_once('../../../config.php');
global $CFG,$PAGE;
require_once($CFG->libdir.'/datalib.php');
require_once('../lib.php');

// catch warnings etc and expunge them!
ob_start();

$context = context_system::instance();
$PAGE->set_context($context);
if (!isloggedin() || !has_capability('moodle/site:config', $context)){
    echo json_encode(array('success' => 'false', 'message' => get_string('sessionerroruser', 'error'), 'redirect' => $CFG->wwwroot.'/login/index.php'));
    exit;
}

$action      = optional_param('action','get',PARAM_ALPHA);
$results     = array();

ob_clean();
header('Content-type: application/json');
ob_flush();

switch ($action) {
    case 'get' :
        // all actions return a result set, so get does nothing special ...
        $results['success'] = true;
        break;
    case 'toggleschool' :
        $school = optional_param('school',0,PARAM_INT);
        $results['success'] = moderngovernor_toggle_school($school);
        break;
    case 'combine' :        
        $schoolids = optional_param('schoolids','',PARAM_SEQUENCE);
        $newlea    = optional_param('newlea','',PARAM_INT);
        $newname   = optional_param('newname','',PARAM_TEXT);
        $results['success'] = moderngovernor_combine_schools($newname, $newlea, $schoolids);
        break;
    default:
        break;
}

// always populate the datatable
$lea         = optional_param('lea', 0,PARAM_INT);
$search      = optional_param('search', '', PARAM_TEXT);
$status      = optional_param('status', 0, PARAM_INT);
$page        = optional_param('page', 1, PARAM_INT);                    
$perpage     = optional_param('perpage', 40, PARAM_INT);              
$sort        = optional_param('sort', '', PARAM_TEXT);            
$sortdir     = optional_param('sortdir', 'ASC', PARAM_TEXT);

if (!empty($sort)) {
    $sort = "{$sort} {$sortdir}";
}

$start = ($page-1)*$perpage;

$results['total'] = get_moderngovernor_school_count($lea,$search, $status-1);
$results['start'] = $start;
$results['data'] = get_moderngovernor_schools($lea, $search, $status-1, $start, $perpage, $sort);

// any warnings or debug info generated by previous functions will now be washed away ...
ob_clean();
ob_end_clean();

// output some nice clean json
echo json_encode($results);

die;

