<?php

require_once('../../../config.php');
global $CFG,$PAGE;
require_once($CFG->libdir.'/datalib.php');
require_once('../lib.php');

// catch warnings etc and expunge them!
ob_start();

$context = context_system::instance();
$PAGE->set_context($context);
if (!isloggedin() || !has_capability('moodle/site:config', $context)){
    echo json_encode(array('success' => 'false', 'message' => get_string('sessionerroruser', 'error'), 'redirect' => $CFG->wwwroot.'/login/index.php'));
    exit;
}

$userid      = optional_param('userid',0,PARAM_INT);
$confirm     = optional_param('confirm',0,PARAM_INT);
$reset       = optional_param('reset',0,PARAM_INT);
$results     = array();

ob_clean();
header('Content-type: application/json');
ob_flush();

if (!empty($userid) && !empty($confirm)) {
    $results['success'] = moderngovernor_confirm_user($userid);
}

if (!empty($userid) && !empty($reset)) {
    $results['success'] = moderngovernor_reset_user($userid);
}

// always populate the datatable
$search      = optional_param('search', '', PARAM_TEXT);
$page        = optional_param('page', 1, PARAM_INT);      
$status      = optional_param('status', 0, PARAM_INT);                      
$perpage     = optional_param('perpage', 40, PARAM_INT);              
$sort        = optional_param('sort', '', PARAM_TEXT);            
$sortdir     = optional_param('sortdir', 'ASC', PARAM_TEXT);

if (!empty($sort)) {
    $sort = "{$sort} {$sortdir}";
}

$start = ($page-1)*$perpage;
--$status;

$results['total'] = get_moderngovernor_unconfirmed_users_count($search, $status);
$results['start'] = $start;
$results['data'] = moderngovernor_get_unconfirmed_users($search, $status, $start, $perpage, $sort);

// any warnings or debug info generated by previous functions will now be washed away ...
ob_clean();
ob_end_clean();

// output some nice clean json
echo json_encode($results);

die;

